modeler.analyze=function(b){var e=this.scenario.loop;if(0==e.length)window.alert("No reentry loop is defined for this scenario");else{for(var d=300,c,g,a,f,l,h,k,n=0;50>n;n++){var m=0;for(g=c=0;g<e.length;g++)a=this.links[e[g]],f=a.from,l=a.erp,h=f.erp,k=d/a.scale-l,h=d/f.scale-h,l=evaluate(a.erp0,d/a.scale,k),h=evaluate(f.erp0,d/f.scale,h),k=evaluate(a.delay0,d/a.scale,k),m+=k*a.scale,c=Math.max(c,l*a.scale,k*a.scale,h*f.scale),a.erp=l,f.erp=h;d=.2*m+.8*d;if(.5>Math.abs(d-m))break}if(d>=c)if(b){controller.cardiovert();
b=viewer.tick-d;for(g=0;g<e.length;g++)f=a.from,f.t0=b,f.erp0&&(h=d/f.scale-f.erp,f.erp=evaluate(f.erp0,d/f.scale,h)),f.state=0,a=this.links[e[g]],a.t0=b,k=d/a.scale-a.erp,a.erp=evaluate(a.erp0,d/a.scale,k),a.delay=evaluate(a.delay0,d/a.scale,k),a.state=0,b+=a.delay;a.state=3;a.to.stim(viewer.tick,a.from)}else window.alert("Reentry is possible at a cycle length of "+Math.round(d)+"ms with the loop ERP of "+Math.round(c)+"ms");else window.alert("Reentry is not possible, the expected cycle length is "+
Math.round(d)+"ms and the loop ERP is "+Math.round(c)+"ms")}};modeler.detect_circuit=function(){function b(d){if(null!=d.path){var c=d,e="";do{var a=c.path;e=e+c.name+"("+a.name+")";c=a.forward?a.to:a.from}while(d!=c);e+=d.name;window.alert(e);return!0}for(c in d.out)if(a=d.out[c],9!=a.state)if(d.path=a,a.forward&&a.from==d){if(b(a.to))return!0}else if(!a.forward&&a.to==d&&b(a.from))return!0;d.path=null;return!1}for(var e in this.nodes)this.nodes[e].path=null;b(this.nodes.av)||b(this.nodes.rv)||window.alert("No reentry circuit found.")};
function Node(){this.t0=this.state=0;this.erp=200;this.cl=Math.MAX_VALUE;this.mean_cl=650;this.out=[];this.name="<>";this.paced=0;this.scale=1;this.cl0=this.erp0=this.path=null}
Node.prototype={constructor:Node,stim:function(b,e){if(0==this.state){var d=(b-this.t0)/this.scale-this.erp;this.erp=evaluate(this.erp0,(b-this.t0)/this.scale,d);this.mean_cl=.1*(b-this.t0)/this.scale+.9*this.mean_cl;this.cl=evaluate(this.cl0,this.mean_cl,d);this.update(b);intervals.update(this.name,b);this.t0=b;this.state=2;for(var c in this.out)this.out[c].stim(b,this);this.state=1}9==this.state||"@"!=e.name.charAt(0)&&"#"!=e.name.charAt(0)||(this.paced=b)},update:function(b){},run:function(b){0==
this.state&&b>=this.t0+this.cl?this.stim(b,this):1==this.state&&b>=this.t0+this.erp*this.scale&&(this.paced=this.state=0)},egm:function(b,e,d){var c=b-this.t0;return.02*Math.random()+(c>e?0:Math.sin(c*Math.PI/e)*(Math.abs(c/d-Math.floor(c/d+.5))-.25))+(this.paced?1/(b-this.paced+1):0)},reset:function(b){this.t0=b;this.state=0}};function create_node(b,e,d){var c=new Node;c.name=b;c.erp0=e;c.cl0=d;return c}function create_add_node(b,e,d){return modeler.nodes[b]=create_node(b,e,d)}
function Link(){this.t0=this.state=0;this.erp=200;this.delay=100;this.source=this.to=this.from=null;this.name="->";this.scale=1;this.forward=!1;this.delay0=this.erp0=null}
Link.prototype={constructor:Link,stim:function(b,e){if(0==this.state){this.source=e;this.forward=this.from==this.source;this.state=1;var d=(b-this.t0)/this.scale-this.erp;this.erp=evaluate(this.erp0,(b-this.t0)/this.scale,d);this.delay=evaluate(this.delay0,(b-this.t0)/this.scale,d);this.update(b);0>this.delay&&(this.state=3);this.t0=b}},update:function(b){},run:function(b){1==this.state&&b>=this.t0+this.delay*this.scale&&(this.state=2,this.from==this.source&&this.to.stim(b,this),this.to==this.source&&
this.from.stim(b,this),this.state=3);3==this.state&&b>=this.t0+this.erp*this.scale&&(this.state=0)},reset:function(b){this.t0=b;this.state=0}};function create_link(b,e,d,c,g,a){var f=new Link;f.from=e;f.to=d;e.out.push(f);c&&d.out.push(f);f.erp0=a;f.delay0=g;f.name=b;return f}function create_add_link(b,e,d,c,g,a){return modeler.links[b]=create_link(b,e,d,c,g,a)}
function evaluate(b,e,d){if(null==b)return Math.MAX_VALUE;if("number"==typeof b)return b;if(!$.isArray(b))return null;var c,g=0;if("string"!=typeof b[0]){for(c=0;c<b.length;c++)g+=evaluate(b[c],e);return g}var a=Array(b.length);for(c=1;c<b.length;c++)a[c]=evaluate(b[c],e);switch(b[0]){case "add":for(c=1;c<b.length;c++)g+=a[c];return g;case "tau":switch(c=a[1],b.length){case 2:return e<c?Math.MAX_VALUE:0;case 3:return e<c?Math.MAX_VALUE:a[2];case 4:return e<c?a[3]:a[3]*Math.exp(-(e-c)/a[2]);case 5:return a[4]+
(e<c?a[3]:a[3]*Math.exp(-(e-c)/a[2]));case 6:return e<c?a[3]+a[5]:a[3]*Math.exp(-(e-c)/a[2])+a[5]*Math.exp(-(e-c)/a[4]);case 7:return a[6]+(e<c?a[3]+a[5]:a[3]*Math.exp(-(e-c)/a[2])+a[5]*Math.exp(-(e-c)/a[4]))}case "tau*":switch(c=a[1],b.length){case 2:return d<c?Math.MAX_VALUE:0;case 3:return d<c?Math.MAX_VALUE:a[2];case 4:return d<c?a[3]:a[3]*Math.exp(-(d-c)/a[2]);case 5:return a[4]+(d<c?a[3]:a[3]*Math.exp(-(d-c)/a[2]));case 6:return d<c?a[3]+a[5]:a[3]*Math.exp(-(d-c)/a[2])+a[5]*Math.exp(-(d-c)/
a[4]);case 7:return a[6]+(d<c?a[3]+a[5]:a[3]*Math.exp(-(d-c)/a[2])+a[5]*Math.exp(-(d-c)/a[4]))}case "sel":switch(b.length){case 2:return a[1]*Math.random();case 3:return a[2]+a[1]*Math.random();case 4:return Math.random()<a[1]?a[2]:a[3]}}}function Intervals(){this.h1=this.h0=this.r2=this.r1=this.r0=this.a1=this.a0=this.p2=this.p1=this.p0=0}
Intervals.prototype={constructor:Intervals,update:function(b,e){("hra"==b||"ra1"==b)&&e-this.p0>viewer.margin?(this.p2=this.p1,this.p1=this.p0,this.p0=e):("sept"==b||"rv"==b||"lv"==b)&&e-this.r0>viewer.margin?(this.r2=this.r1,this.r1=this.r0,this.r0=e):"his"==b?(this.h1=this.h0,this.h0=e):"av"==b&&(this.a1=this.a0,this.a0=e)}};
