{
    "nodes":{        
        "hra":{
            "erp":200,
            "cl":null
        },
        "sinus":{
            "erp":250,
            "cl":["tau", 250, 200, 100, 750]
        },
        "atrium":{
            "erp":150,
            "cl":null
        },
        "av":{
            "erp":200,
            "cl":null
        },
        "cspa":{
            "erp":200,
            "cl":null
        },
        "csma":{
            "erp":200,
            "cl":null
        },
        "csda":{
            "erp":200,
            "cl":null
        },
        "his0":{
            "erp":200,
            "cl":null
        },
        "his":{
            "erp":200,
            "cl":null
        },
    	"his1":{
            "erp":200,
            "cl":null
        },
        "sept":{
            "erp":220,
            "cl":null
        },
        "rv":{
            "erp":150,
            "cl":null
        },
        "lv":{
            "erp":150,
            "cl":null
        },
        "cspv":{
            "erp":150,
            "cl":null
        },
        "csmv":{
            "erp":150,
            "cl":null
        },
        "csdv":{
            "erp":150,
            "cl":null
        },        
        "sss:sinus":{
            "erp":300,
            "cl":["tau", 300, 100, 2000, 500]
        },
        "sinus_tachy":{
            "erp":250,
            "cl":["tau", 250, 200, 100, 550]
        },
        "sinus_brady":{
            "erp":250,
            "cl":["tau", 250, 200, 100, 1250]
        },
        "at_focus":{
            "erp":200,
            "cl":["sel", 0.15, 500, 3000]
        },
        "pvc_focus":{
            "erp":200,
            "cl":["sel", 0.2, 500, 3000]
        },
        "jet_focus":{
            "erp":200,
            "cl":["sel", ["tau", 350, 150, 0, 0.99], 350, 1000]
        },
		"avb3:avn":{
			"erp":200,
			"cl":["tau", 250, 200, 100, 800]
		},
		"parahisian":{
			"erp":150,
			"cl":null
		}
    },    
    "links":{
        "sinus->atrium":{
            "from":"sinus",
            "to":"atrium",
            "erp":200,
            "delay":20,
            "bi":true            
        },
		"sinuatrial:sinus->atrium":{
            "from":"sinus",
            "to":"atrium",
            "erp":200,
            "delay":["sel",0.8,20,-1],
            "bi":true            
        },
        "hra->atrium":{
            "from":"hra",
            "to":"atrium",
            "erp":200,
            "delay":20,
            "bi":true           
        },    
        "atrium->av":{
            "from":"atrium",
            "to":"av",
            "erp":200,
            "delay":30,
            "bi":true
        },
        "av->cspa":{
            "from":"av",
            "to":"cspa",
            "erp":200,
            "delay":["tau", 200, 100, 20, 10],
            "bi":true
        },
        "cspa->csma":{
            "from":"cspa",
            "to":"csma",
            "erp":200,
            "delay":20,
            "bi":true
        },
        "csma->csda":{
            "from":"csma",
            "to":"csda",
            "erp":200,
            "delay":20,
            "bi":true
        },
        "fast":{
            "from":"av",
            "to":"his0",
            "erp":330,
            "delay":["tau", 330, 20, 40, 60],
            "bi":true
        },
        "lower_common":{
            "from":"his0",
            "to":"his",
            "erp":180,
            "delay":20,
            "bi":true
        },
        "avnrt_block:lower_common":{
            "from":"his0",
            "to":"his",
            "erp":350,
            "delay":20,
            "bi":true
        },
		"infra_his":{
            "from":"his",
            "to":"his1",
            "erp":150,
            "delay":0,
            "bi":true
        },
        "his->sept":{
            "from":"his1",
            "to":"sept",
            "erp":180,
            "delay":40,
            "bi":false
        },
        "his->rv":{
            "from":"his1",
            "to":"rv",
            "erp":240,
            "delay":80,
            "bi":true
        },
        "his->lv":{
            "from":"his1",
            "to":"lv",
            "erp":210,
            "delay":60,
            "bi":true
        },        
        "rv->lv":{
            "from":"rv",
            "to":"lv",
            "erp":150,
            "delay":["tau", 150, 100, -50,60],
            "bi":false
        },
        "lv->cspv":{
            "from":"lv",
            "to":"cspv",
            "erp":150,
            "delay":10,
            "bi":true
        },
        "lv->csmv":{
            "from":"lv",
            "to":"csmv",
            "erp":150,
            "delay":30,
            "bi":true
        },
        "lv->csdv":{
            "from":"lv",
            "to":"csdv",
            "erp":150,
            "delay":50,
            "bi":true
        },
        "cspv->csmv":{
            "from":"cspv",
            "to":"csmv",
            "erp":150,
            "delay":20,
            "bi":true
        },
        "csmv->csdv":{
            "from":"csmv",
            "to":"csdv",
            "erp":150,
            "delay":20,
            "bi":true
        },        
        "slow":{
            "from":"av",
            "to":"his0",
            "erp":260,
            "delay":["tau", 260, 50, 120, 250],
            "bi":true
        },
		"basic:slow":{
            "from":"av",
            "to":"his0",
            "erp":260,
            "delay":["tau", 260, 50, 120, 250],
            "bi":false
        },
        "slow0":{
            "from":"av",
            "to":"his0",
            "erp":260,
            "delay":["tau", 260, 10, 50, 200],
            "bi":true
        },        
        "sss:sinus->atrium":{
            "from":"sss:sinus",
            "to":"atrium",
            "erp":200,
            "delay":20,
            "bi":true            
        },
        "sinus_tachy->atrium":{
            "from":"sinus_tachy",
            "to":"atrium",
            "erp":200,
            "delay":20,
            "bi":true            
        },
        "sinus_brady->atrium":{
            "from":"sinus_brady",
            "to":"atrium",
            "erp":200,
            "delay":20,
            "bi":true            
        },
        "avrt:lat_manifest":{
            "from":"csda",
            "to":"csdv",
            "erp":150,
            "delay":80,
            "bi":true            
        },
        "avrt:lat_concealed":{
            "from":"csdv",
            "to":"csda",
            "erp":150,
            "delay":["tau", 310, 50, 40, 40],
            "bi":false            
        },
        "avrt:lat:av->cspa":{
            "from":"av",
            "to":"cspa",
            "erp":200,
            "delay":30,
            "bi":true
        },
        "at_link":{
            "from":"at_focus",
            "to":"av",
            "erp":150,
            "delay":10,
            "bi":true
        },
        "jet_link":{
            "from":"jet_focus",
            "to":"his0",
            "erp":150,
            "delay":10,
            "bi":true
        },
        "vt:sept->lv":{
            "from":"sept",
            "to":"lv",
            "erp":150,
            "delay":80,
            "bi":true
        },
        "vt:his->lv":{
            "from":"his1",
            "to":"lv",
            "erp":260,
            "delay":180,
            "bi":true
        },
        "vt:rv->lv":{
            "from":"rv",
            "to":"lv",
            "erp":150,
            "delay":80,
            "bi":false
        },
		"avb1:fast":{
            "from":"av",
            "to":"his0",
            "erp":330,
            "delay":["tau", 330, 50, 100, 150],
            "bi":true
        },
		"avb2a:fast":{
            "from":"av",
            "to":"his0",
            "erp":["tau*", 550, 50, 200, 550],
            "delay":["tau*", 0, 20, 40, 60],
            "bi":true
        },
		"avb2b:infra_his":{
            "from":"his",
            "to":"his1",
            "erp":["tau*", 550, 50, 200, 550],
            "delay":0,
            "bi":true
        },
		"avb3:avn->his":{
            "from":"avb3:avn",
            "to":"his",
            "erp":150,
            "delay":0,
            "bi":true
        },
        "pvc_link":{
            "from":"pvc_focus",
            "to":"rv",
            "erp":150,
            "delay":20,
            "bi":true
        }
    },         
    "scenarios":{
        "s_nsr":{
            "nodes":["hra","sinus","atrium","av","cspa","csma","csda","his0",
                "his","his1","sept","rv","lv","cspv","csmv","csdv","parahisian"],
            "links":["sinus->atrium","hra->atrium","atrium->av","av->cspa",
                "cspa->csma","csma->csda","fast","lower_common","infra_his",
				"his->sept","his->rv","his->lv","rv->lv","lv->cspv",
				"lv->csmv","lv->csdv","cspv->csmv","csmv->csdv"],
            "base":null,
            "channels": ["V1", "LV", "RV", "AO", "PA", "PCW", "CVP"],
            "caption":"Normal sinus rhythm",
            "loop":[],
            "hint":"try complete EPS!"            
        },
        "s_tachy":{
            "nodes":["-sinus", "sinus_tachy"],
            "links":["-sinus->atrium", "sinus_tachy->atrium"],
            "base":"s_nsr",
            "channels": ["V1", "LV", "RV", "AO", "PA", "PCW", "CVP"],
            "caption":"Sinus tachycardia",
            "loop":[],
            "hint":""  
        },
        "s_brady":{
            "nodes":["-sinus", "sinus_brady"],
            "links":["-sinus->atrium", "sinus_brady->atrium"],
            "base":"s_nsr",
            "channels": ["V1", "LV", "RV", "AO", "PA", "PCW", "CVP"],
            "caption":"Sinus bradycardia",
            "loop":[],
            "hint":""  
        },
        "s_apc":{
            "nodes":["at_focus"],
            "links":["at_link"],
            "base":"s_nsr",
            "channels": ["V1", "LV", "RV", "AO", "PA", "PCW", "CVP"],
            "caption":"Sinus rhythm with APC",
            "loop":[],
            "hint":""  
        },
        "s_pvc":{
            "nodes":["pvc_focus"],
            "links":["pvc_link"],
            "base":"s_nsr",
            "channels": ["V1", "LV", "RV", "AO", "PA", "PCW", "CVP"],
            "caption":"Sinus rhythm with PVC",
            "loop":[],
            "hint":""  
        }				
    }
}
